// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0
// source: explore/explore.proto

package explore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExploreServiceClient is the client API for ExploreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExploreServiceClient interface {
	LikedYou(ctx context.Context, in *LikedYouRequest, opts ...grpc.CallOption) (*LikedYouResponse, error)
	PutSwipe(ctx context.Context, in *PutSwipeRequest, opts ...grpc.CallOption) (*PutSwipeResponse, error)
}

type exploreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExploreServiceClient(cc grpc.ClientConnInterface) ExploreServiceClient {
	return &exploreServiceClient{cc}
}

func (c *exploreServiceClient) LikedYou(ctx context.Context, in *LikedYouRequest, opts ...grpc.CallOption) (*LikedYouResponse, error) {
	out := new(LikedYouResponse)
	err := c.cc.Invoke(ctx, "/explore.ExploreService/LikedYou", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exploreServiceClient) PutSwipe(ctx context.Context, in *PutSwipeRequest, opts ...grpc.CallOption) (*PutSwipeResponse, error) {
	out := new(PutSwipeResponse)
	err := c.cc.Invoke(ctx, "/explore.ExploreService/PutSwipe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExploreServiceServer is the server API for ExploreService service.
// All implementations must embed UnimplementedExploreServiceServer
// for forward compatibility
type ExploreServiceServer interface {
	LikedYou(context.Context, *LikedYouRequest) (*LikedYouResponse, error)
	PutSwipe(context.Context, *PutSwipeRequest) (*PutSwipeResponse, error)
	mustEmbedUnimplementedExploreServiceServer()
}

// UnimplementedExploreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExploreServiceServer struct {
}

func (UnimplementedExploreServiceServer) LikedYou(context.Context, *LikedYouRequest) (*LikedYouResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikedYou not implemented")
}
func (UnimplementedExploreServiceServer) PutSwipe(context.Context, *PutSwipeRequest) (*PutSwipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutSwipe not implemented")
}
func (UnimplementedExploreServiceServer) mustEmbedUnimplementedExploreServiceServer() {}

// UnsafeExploreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExploreServiceServer will
// result in compilation errors.
type UnsafeExploreServiceServer interface {
	mustEmbedUnimplementedExploreServiceServer()
}

func RegisterExploreServiceServer(s grpc.ServiceRegistrar, srv ExploreServiceServer) {
	s.RegisterService(&ExploreService_ServiceDesc, srv)
}

func _ExploreService_LikedYou_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikedYouRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExploreServiceServer).LikedYou(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/explore.ExploreService/LikedYou",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExploreServiceServer).LikedYou(ctx, req.(*LikedYouRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExploreService_PutSwipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutSwipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExploreServiceServer).PutSwipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/explore.ExploreService/PutSwipe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExploreServiceServer).PutSwipe(ctx, req.(*PutSwipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExploreService_ServiceDesc is the grpc.ServiceDesc for ExploreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExploreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "explore.ExploreService",
	HandlerType: (*ExploreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LikedYou",
			Handler:    _ExploreService_LikedYou_Handler,
		},
		{
			MethodName: "PutSwipe",
			Handler:    _ExploreService_PutSwipe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "explore/explore.proto",
}
