services:
  dynamodb-local:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./data:/home/dynamodblocal/data"
      - "./init:/init"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=local
